[package]
name = "tuic-quinn"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = { version = "0.1.62", default-features = false }
bytes = { version = "1.3.0", default-features = false, features = ["std"] }
futures-util = { version = "0.3.25", default-features = false, features = ["io", "std"] }
quinn = { version = "0.9.3", default-features = false, features = ["futures-io"] }
thiserror = { version = "1.0.38", default-features = false }
tuic = { path = "../tuic", default-features = false, features = ["model"] }
