[package]
name = "tuic-server"
version = "0.1.0"
authors = ["EAimTY <ea.imty@gmail.com>"]
description = ""
categories = ["network-programming", "command-line-utilities"]
keywords = ["tuic", "proxy", "quic"]
edition = "2021"
readme = "README.md"
license = "GPL-3.0-or-later"
repository = "https://github.com/EAimTY/tuic"

[dependencies]
tuic-protocol = { path="../protocol" }

anyhow = "1.0"
blake3 = "1.3"
bytes = "1.1"
futures-util = { version = "0.3", default-features = false }
getopts = "0.2"
parking_lot = "0.12"
quinn = { git = "https://github.com/EAimTY/quinn", branch = "0.8.x" }
rustls = { version = "0.20", features = ["quic"], default-features = false }
tokio = { version = "1.17", features = ["io-util", "macros", "rt-multi-thread", "time"] }
