[package]
name = "tuic-server"
version = "0.1.0"
authors = ["EAimTY <ea.imty@gmail.com>"]
description = ""
categories = ["network-programming", "command-line-utilities"]
keywords = ["tuic", "proxy", "quic"]
edition = "2021"
readme = "README.md"
license = "GPL-3.0-or-later"
repository = "https://github.com/EAimTY/tuic"

[dependencies]
tuic-protocol = { path="../protocol" }

bytes = "1.1"
futures-util = { version = "0.3", default-features = false }
getopts = "0.2"
log = "0.4"
quinn = "0.8"
rustls = { version = "0.20", features = ["quic"], default-features = false }
seahash = { version = "4.1", features = ["use_std"] }
simple_logger = { version = "2.1", features = ["timestamps", "stderr"], default-features = false }
thiserror = "1.0"
tokio = { version = "1.16", features = ["io-util", "macros", "rt-multi-thread"] }
