[package]
name = "tuic"
version = "0.1.0"
edition = "2021"

[features]
prototype = ["parking_lot"]

[dependencies]
parking_lot = { version = "0.12.1", default-features = false, optional = true }

[dev-dependencies]
tuic = { path = ".", features = ["prototype"] }
