on:
  workflow_dispatch:
  release:
    types: [published]

name: build-and-release

jobs:
  build-and-release:
    strategy:
      fail-fast: false
      matrix:
        include:
          # x86_64-linux
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            cross: false
            arch-name: x86_64-linux
            file-ext:
          # x86_64-windows
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            cross: false
            arch-name: x86_64-windows
            file-ext: .exe
          # x86_64-macos
          - os: macos-latest
            target: x86_64-apple-darwin
            cross: false
            arch-name: x86_64-macos
            file-ext:
          # aarch64-linux
          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            cross: true
            arch-name: aarch64-linux
            file-ext:
          # aarch64-macos
          - os: macos-latest
            target: aarch64-apple-darwin
            cross: true
            arch-name: aarch64-macos
            file-ext:
          # aarch64-android
          - os: ubuntu-latest
            target: aarch64-linux-android
            cross: true
            arch-name: aarch64-android
            file-ext:
          # aarch64-ios
          - os: macos-latest
            target: aarch64-apple-ios
            cross: true
            arch-name: aarch64-ios
            file-ext:

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get the latest tag
        id: tag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: ${{ matrix.target }}
          override: true

      - name: Build server
        uses: actions-rs/cargo@v1
        with:
          use-cross: ${{ matrix.cross }}
          command: build
          args: --release -p tuic-server --target ${{ matrix.target }}

      - name: Build client
        uses: actions-rs/cargo@v1
        with:
          use-cross: ${{ matrix.cross }}
          command: build
          args: --release -p tuic-client --target ${{ matrix.target }}

      - name: Move binaries
        run: |
          mkdir artifacts/
          mv target/${{ matrix.target }}/release/tuic-server${{ matrix.file-ext }} artifacts/tuic-server-${{ steps.tag.outputs.tag }}-${{ matrix.arch-name }}${{ matrix.file-ext }}
          mv target/${{ matrix.target }}/release/tuic-client${{ matrix.file-ext }} artifacts/tuic-client-${{ steps.tag.outputs.tag }}-${{ matrix.arch-name }}${{ matrix.file-ext }}

      - name: Calculate SHA256
        run: |
          cd artifacts/
          openssl dgst -sha256 -r tuic-server-${{ steps.tag.outputs.tag }}-${{ matrix.arch-name }}${{ matrix.file-ext }} > tuic-server-${{ steps.tag.outputs.tag }}-${{ matrix.arch-name }}${{ matrix.file-ext }}.sha256sum
          openssl dgst -sha256 -r tuic-client-${{ steps.tag.outputs.tag }}-${{ matrix.arch-name }}${{ matrix.file-ext }} > tuic-client-${{ steps.tag.outputs.tag }}-${{ matrix.arch-name }}${{ matrix.file-ext }}.sha256sum

      - name: Release binaries
        uses: ncipollo/release-action@v1
        with:
          artifacts: "artifacts/*"
          tag: ${{ steps.tag.outputs.tag }}
          name: ${{ steps.tag.outputs.tag }}
          allowUpdates: true
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
